### ISSUE TITLE
Misbehavior when build in busybox environment

### ISSUE THREAD

**Issue by duanyao** [concurrencykit/ck#100]
### Versions:
ck master branch.
busybox 1.22.1/1.25.1

### Steps to reproduce:
In a busybox environment, such as [alpine linux](https://alpinelinux.org/), without GNU coreutils installed, run `./configure --prefix=/usr`.

If you don't have such busybox environment, you can install busybox (`apt install busybox` on debians), and modify `./configure`, line 172, change `expr` to `busybox expr`, and then run `./configure --prefix=/usr`.

### Actual result
```
expr: syntax error
...
Headers will be installed in /include
Libraries will be installed in /lib
Documentation will be installed in /share/man
```
It seems `--prefix` is misinterpreted as ""(empty) after a `expr` error.

### Expected result
Headers/Libraries should be installed to `/usr/include` and `/usr/lib`, not `/include` and `/lib`.

### The problem
It seems `./configure` is incompatible with busybox's expr. 

### Suggestion
A simple workaround is installing GNU coreutils, but it would be nicer to make it compatible with busybox. At least, explicitly state that concurrencykit doesn't build in a busybox environment.

**Comment by sbahra** [comment]
Thanks! We'll fix this as soon as possible.

**Comment by sbahra** [comment]
@duanyao This should be fixed now. Could you confirm it all works for you? If so, we can do a patch-level release for this and any other build issues.

**Comment by cognet** [comment]
Hi,

It should now work fine, can you confirm it ?

Thanks !

**Comment by duanyao** [comment]
Thanks! I confirm it works now.
