### ISSUE TITLE
0.6.0 fails to build on PowerPC

### ISSUE THREAD

**Issue by ernsteiswuerfel** [concurrencykit/ck#101]
Tried to build concurrencykit-0.6.0 as it is a dependency for sysbench-1.0.7. Unfortunately building concurrencykit did not work.

My machine:
System:    Host: T801 Kernel: 4.10.17-gentoo ppc64 (32 bit) Desktop: MATE 1.18.0
           Distro: Gentoo Base System release 2.3
Machine:   No /sys/class/dmi; using dmidecode: dmidecode is not installed.
CPU:       Dual core PPC970MP altivec supported (-MCP-) speed/max: 2300.000000MHz/2300 MHz
Graphics:  Card-1: NVIDIA NV43 [GeForce 6600]
           Card-2: Advanced Micro Devices [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series]
           Display Server: X.org 1.19.3 driver: radeon tty size: 132x24 Advanced Data: N/A for root
Network:   Card-1: Broadcom Limited NetXtreme BCM5780 Gigabit Ethernet driver: tg3

build.log:
[build_log.txt](https://github.com/concurrencykit/ck/files/1082808/build_log.txt)

**Comment by sbahra** [comment]
This looks like an environment issue to me @ernsteiswuerfel. Could you confirm that you have glibc development headers installed?

**Comment by ernsteiswuerfel** [comment]
I guess so.

It's a Gentoo Linux, where everything will be compiled from source. You don't need those extra ...-dev packages like on Ubuntu. glibc was compiled with following flags:

[ebuild   R    ] sys-libs/glibc-2.23-r3:2.2::gentoo  USE="rpc -audit -caps -debug -gd (-hardened) (-multilib) -nscd -profile (-selinux) -suid -systemtap -vanilla" 0 KiB
