### ISSUE TITLE
error: assigning to 'struct ck_spinlock_hclh *' from incompatible type 'void *'

### ISSUE THREAD

**Issue by gnobal** [concurrencykit/ck#103]
When trying to incorporate ck spinlock in my code I'm getting errors such as the following:
```
3rdparty/ck-0.6.0/include/spinlock/clh.h:81:13: error: assigning to 'struct ck_spinlock_clh *' from incompatible type 'void *'
        previous = ck_pr_fas_ptr(queue, thread);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
3rdparty/ck-0.6.0/include/spinlock/mcs.h:100:13: error: assigning to 'struct ck_spinlock_mcs *' from incompatible type 'void *'
        previous = ck_pr_fas_ptr(queue, node);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
3rdparty/ck-0.6.0/include/spinlock/hclh.h:89:13: error: assigning to 'struct ck_spinlock_hclh *' from incompatible type 'void *'
        previous = ck_pr_fas_ptr(local_queue, thread);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The compiler used is clang 4.0.0

**Comment by sbahra** [comment]
@gnobal Is this C++? Concurrency Kit is targeting C99+, with a few exceptions.

**Comment by gnobal** [comment]
@sbahra yes. Trying to build for C++ was the issue.
It looks like a few casts would help build on C++ (at least the spinlock part, which is what I was trying to use).
Thanks a lot. Closing this.

**Comment by jimages** [comment]
Although CK is targeting c99+, I think it would be a good idea to support being called from c++ code considering that maintaining the c++ compatible doesn't cost much time. If it sounds good, I would make a PR(some casts) which makes it compatible with c++.

**Comment by sbahra** [comment]
Hi Zachary, it wasn't an easy decision but unfortunately, no plans on treating C++ as a first-class citizen. We plan on using C11+ features. It also means unidiomatic and less safe C code which in many cases will violate the quality standards of the projects it is used in. I would rather see a CK++ project instead, taking advantage of the features of C++.
