### ISSUE TITLE
make check long runtime

### ISSUE THREAD

**Issue by kev009** [concurrencykit/ck#126]
On my Talos, 176 thread make check takes a very long time (over a day).  Setting ./configure --cores=32 makes it about the same speed as my 48 thread amd64, and those are all affined on the same package in ppc64 case (using ppc64le Ubuntu on the Talos).  I don't have a larger amd64 to compare but wondering what could cause that massive runtime increase and if we should offer a light and heavy weight regression for large systems.

**Comment by sbahra** [comment]
That's expected. Make sure you use appropriate thread count and don't over-allocate threads to cores. Since things are busy-waiting, live lock and starvation are real.

**Comment by kev009** [comment]
@sbahra it seems like something more than that.  For instance, running 48 threads on my 48 thread x86 is fully saturated but completes in a fairly quick time.  --cores=32 or whatever on the ppc64 results in similar worst case SMT competition as those tests on 176 threads because of affinities.  Is there some kind of non-linear increase you are expecting from the competition?  Does anyone have access to a massive x86 system?
