### ISSUE TITLE
detecting RTM?

### ISSUE THREAD

**Issue by teamblubee** [concurrencykit/ck#134]
Hello

I was looking over the source code and saw there's a FreeBSD specific include dealing with cachelines; https://github.com/concurrencykit/ck/blob/master/include/freebsd/ck_md.h.in

What exactly does: detect RTM mean ? What is RTM?

**Comment by sbahra** [comment]
Hi,

That refers to "restricted transactional memory", see https://en.wikipedia.org/wiki/Transactional_Synchronization_Extensions#Restricted_Transactional_Memory.

For questions, let's use Google Group linked to at https://concurrencykit.org.
