### ISSUE TITLE
ck_ec and ck_hs tests dump core on FreeBSD

### ISSUE THREAD

**Issue by lwhsu** [concurrencykit/ck#138]
ck_ec and ck_hs tests dump core on FreeBSD. Tested on FreeBSD amd64 12.0-RELEASE and -CURRENT.

While ck_ec seems not supporting FreeBSD at this moment, but these tests would be better to just exit on OSX instead of dumping core.

**Comment by sbahra** [comment]
We'll update `ck_ec` to work on FreeBSD. Could you share logs and more details of these failures? Output of make check would be useful as well as any accompanied backtraces.

**Comment by cognet** [comment]
I'll have a look at FreeBSD issues

**Comment by sbahra** [comment]
ck_ec has not been tested on FreeBSD, but as it's mostly freestanding (and tested on both clang and gcc), there isn't a good reason we don't add umutex coverage as well.

ck_hs has been fixed, this was an invalid test that was introduced with ck_hs_next_spmc a while ago.

Worth adding valgrind and ASAN to our tests.

**Comment by sbahra** [comment]
ck_ec is fixed now as well, underlying root cause was GNU makeism for the tests. Thanks for reporting!
