### ISSUE TITLE
gettid from regressions/common.h clashes with glibc 2.30 provided one

### ISSUE THREAD

**Issue by StefanBruens** [concurrencykit/ck#147]
https://github.com/concurrencykit/ck/blob/f37aa8bed6114035343bf61e277b499855b75b36/regressions/common.h#L269-L275

glibc 2.30 added a wrapper around the syscall:
https://lwn.net/Articles/795127/

As the wrapper is a function and not a macro, the "#ifdef gettid" check does not work. The gettid() availability should be checked in configure.

**Comment by sbahra** [comment]
Fix incoming, thank you @StefanBruens!
