### ISSUE TITLE
Configurable doc compression

### ISSUE THREAD

**Issue by hydrapolic** [concurrencykit/ck#150]
In Gentoo Linux we compress all documentation. Since ck already does the compression, it would lead to double compression. Would it be possible to pass an argument  to ./configure whether we want documentation compression?

Thank you

**Comment by sbahra** [comment]
Sure! We can add this. What's the preferred idiom / name for such an option?

**Comment by hydrapolic** [comment]
Doesn't matter at all, but google returned some results for DOC_COMPRESS.

**Comment by sbahra** [comment]
Ok. This is now possible in master by setting GZIP to an empty string. For example:
```
GZIP="" ./configure
```
Sorry it took a while!

**Comment by hydrapolic** [comment]
Cool, thanks.
