### ISSUE TITLE
0.7.0 Test ck_hclh fails on armv7hl and aarch64

### ISSUE THREAD

**Issue by fila43** [concurrencykit/ck#153]
I am trying build and test 0.7.0 on arm(Fedora 32) and tests fail with:
```
./ck_hclh 5 1
Creating threads (mutual exclusion)...done
Waiting for threads to finish correctness regression...make[2]: *** [Makefile:13: check] Segmentation fault (core dumped)
```
I am attaching full log:
https://fjanus.fedorapeople.org/build.log

**Comment by cognet** [comment]
Hi, I can't seem to reproduce it.
How many cores does your machine have ? And which gcc version is this ?

Thanks !

**Comment by fila43** [comment]
Hi, 
thanks for fast response, in both cases it fails with 5 CPU and gcc version is: 
```gcc                   aarch64       10.0.1-0.7.fc32```

**Comment by fila43** [comment]
It looks like it only occurs with 5 cores, 8 cores with the same software configuration succeeds

**Comment by cognet** [comment]
@fila43 is it better now ?

**Comment by fila43** [comment]
@cognet now test ck_hclh looks fine, but other tests fail with 
make[2]: *** [Makefile:10: check] Segmentation fault (core dumped)
here I have log: https://fjanus.fedorapeople.org/build-i686.log

**Comment by sbahra** [comment]
Sorry this slipped through the cracks @fila43! Thank you for running these tests. We'll investigate more on our side.

Would it be possible to get core dumps? We are unable to recreate on our side. Let's track this on a separate issue though. I see it's impacting both ck_hp_stack and ck_stack. Confirming your logs, this is impacting x86 only?
