### ISSUE TITLE
CK in userspace

### ISSUE THREAD

**Issue by maisheri** [concurrencykit/ck#154]
Hi All,

Have we tried to use the CK for userspace applications ? Any feedback/insights in this direction would be of great help!

maisheri

**Comment by sbahra** [comment]
Hi,

Yes, CK is used on many. I suggest using the Google Group (https://groups.google.com/forum/#!forum/concurrencykit) for support questions! Folks will be able to help better there. We use issues here primarily for tracking bugs and similar.
