### ISSUE TITLE
Add atomic operation

### ISSUE THREAD

**Issue by dangyajun** [concurrencykit/ck#155]
Missing  the compitable or similiar  atomic operation implementation of stdatomic.h or atomic.h

**Comment by sbahra** [comment]
Hi @dangyajun, I would like to better understand the ask here.

Concurrency Kit currently provides a lot more atomic operations than `stdatomic`. See http://concurrencykit.org/doc/ck_pr.html.

Was there something missing? Or are you asking for an interface that is compatible with `stdatomic`?

**Comment by dangyajun** [comment]
Yes, I think compatible interfaces with stdatomic.h is necessary for porting.

**Comment by sbahra** [comment]
Are you referring to having a stdatomic backend for ck_pr? There is a GCC built-in port already that uses __sync-primitives and ACCESS_ONCE semantics. This can be used on any target GCC supports. For example, try passing `--use-cc-builtins` to configure.

What platform are you targeting?
