### ISSUE TITLE
When is the next release of ConcurrencyKit？

### ISSUE THREAD

**Issue by yuanxinkun** [concurrencykit/ck#192]
When is the next release of ConcurrencyKit？

**Comment by sbahra** [comment]
Most folks are just working off of master or a particular commit. There isn't one planned just yet.

**Comment by nmeum** [comment]
> Most folks are just working off of master or a particular commit.

Hi, just quickly wanted to chime in here: I maintain a concurrencykit package for Alpine Linux and (just like other Linux distributions) we focus on packaging upstream releases and for packaging purposes it would therefore be cool if you could tag a new release at some point.

Thanks for your consideration.
