### ISSUE TITLE
Missing man pages for newer fence types

### ISSUE THREAD

**Issue by mhorne** [concurrencykit/ck#202]
I noticed that the following fences are lacking documentation:
1. `ck_pr_fence_lock()`
2. `ck_pr_fence_unlock()`
3. `ck_pr_fence_acqrel()`

The latter has intuitive semantics, but the *lock variants don't.

**Comment by sbahra** [comment]
Will address, thanks. Commit message (1537c8091da102c649b7335d0de7d4005c510ac4) has some more details on lock / unlock, not relevant to most platforms.
