### ISSUE TITLE
Can we get a stable 0.7.1 release?

### ISSUE THREAD

**Issue by tillkruss** [concurrencykit/ck#209]
It's been two years 😬

**Comment by kloczek** [comment]
You mean 0.7.2 😋

**Comment by tillkruss** [comment]
No, even just a stable `0.7.1` that's not a pre-release.

**Comment by pkhuong** [comment]
Yeah, that makes sense. I don't have a lot of time for open source right now. I'll have to triage through the current open issues and see what we want to fix before cutting a release.

**Comment by michael-grunder** [comment]
A release would be great. Please let me know if I can help in any way.

**Comment by michael-grunder** [comment]
This can be closed since v0.7.2 has been released :tada:
