### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [concurrencykit/ck#31]
I find that include guards like "[CK_HP_H](https://github.com/concurrencykit/ck/blob/554e2f0874baddf957388add4f7868fb18083ddc/include/ck_hp.h#L27)" and "[CK_PR_H](https://github.com/concurrencykit/ck/blob/554e2f0874baddf957388add4f7868fb18083ddc/include/ck_pr.h#L28)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by sbahra** [comment]
Why? These all follow strict namespacing, with `_H`-suffix being treated as an exception (as separate namespace).

**Comment by elfring** [comment]
Would you like to reduce the probability for name clashes a bit more?
How do you think about to make [include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by sbahra** [comment]
It isn't necessary. Namespace conventions provide us conflict-freedom.

**Comment by elfring** [comment]
A prefix that is longer than "CK" might also help to make the source file reuse a bit safer.
