### ISSUE TITLE
Ck fails to build from source if default gcc/ck_pr.h is used

### ISSUE THREAD

**Issue by juricast** [concurrencykit/ck#35]
gcc version 4.9.2 (Debian 4.9.2-16) 
Target: x86_64-linux-gnu
ck: ck (0.4.4-1) Debian

Hello,

I am trying to build Debian package ck 0.4.4-1 on MIPS and MIPS64.
While trying to build this package I had problems with ck_epoch_synchronize test.
ck_epoch_synchronize test starts and never ends. It is running on all cores (100%) for hours.

Mips is not listed in include/ck_pr.h so for mips build gcc/ck_pr.h is used.
<pre>
#if defined(__GNUC__)
#include "gcc/ck_pr.h"
#endif
</pre>

I have changed define for x86_64 to test this issue on Intel: 
<pre>
diff -upNr ck-0.4.4-orig/include/ck_pr.h ck-0.4.4/include/ck_pr.h
--- ck-0.4.4-orig/include/ck_pr.h       2014-09-02 02:48:38.000000000 +0000
+++ ck-0.4.4/include/ck_pr.h    2015-05-06 11:31:44.606055785 +0000
@@ -35,7 +35,7 @@
 #include <stdbool.h>

 #if defined(__x86_64__)
-#include "gcc/x86_64/ck_pr.h"
+#include "gcc/ck_pr.h"
 #elif defined(__x86__)
 #include "gcc/x86/ck_pr.h"
 #elif defined(__sparcv9__)
 </pre>

And when I use same gcc/ck_pr.h as for MIPS(64) package again run test for hours (22+), and does not end, on all cores on Intel i7 CPU.
(./ck_epoch_synchronize `expr 8 / 2` `expr 8 / 2` 1)

Help or suggestions are welcomed.

Thanks!

Regards,
Jurica

**Comment by sbahra** [comment]
Thanks for the report. ck_epoch_synchronize can indeed take a very very long time to complete if cores are very much contended. However, 22 hours is pretty intense. I'll take a look at potential gcc/ck_pr.h regressions tonight. Note that `gcc/ck_pr.h` is only meant to serve as a lay-over until a native port is developed (it is meant to be used by porters). Regardless, it shouldn't behave this way.

**Comment by sbahra** [comment]
@cognet is on it. I expect fix to be committed this evening to master.

**Comment by sbahra** [comment]
Fixed in master, thanks! (https://github.com/concurrencykit/ck/commit/63d6c00c3dad03bd7556057a85016f31e929f0f1)
