### ISSUE TITLE
configure for a 'gcc builtins' (non-native) port?

### ISSUE THREAD

**Issue by mhaberler** [concurrencykit/ck#51]
http://concurrencykit.org/community.html 8) says: 

> If you don't want a native port, Concurrency Kit will drop-back to using GCC atomic intrinsics. 

how do I achieve that? 

It might be useful for us - as a baseline package which works everywhere, maybe just not with stellar performance

**Comment by sbahra** [comment]
That page is old, I should probably remove it. Right now there is no automatic "GCC" platform. We can add support for configure to do this, let's create a feature issue to track it, happy to discuss specifics there.

Basically, if no first-class platform is detected, we can just fallback and use a build.gcc. The work involved is minimal.

**Comment by cognet** [comment]
I added a configure option to force the use of the gcc bulitins, even if the platform is known and supported

**Comment by sbahra** [comment]
Do we fall back to this option if it is detected that the current platform is unsupported?

**Comment by mhaberler** [comment]
with a notice - ok
not sure if "supported" will be a configure-only property, it might need a compile test due to compiler defaults diverging from arch/uname -m output

**Comment by cognet** [comment]
Right now configure will stop if it doesn't recognize the machine, it can easily be changed, though we should probably require a few informations from the user then, ie the memory model (or shall we default to RMO ?)

**Comment by cognet** [comment]
There's a few thing we'd have to deal with, too, as showed by the mips thing, such as the generic code assuming it can emit a 64bits CAS when it may not.

**Comment by sbahra** [comment]
We should default to RMO.

**Comment by sbahra** [comment]
@cognet Should this ticket be closed out?

**Comment by cognet** [comment]
Yup it should be fine
