### ISSUE TITLE
Problems using CK_LIST

### ISSUE THREAD

**Issue by 2trill2spill** [concurrencykit/ck#60]
I'm trying to use concurrencykit in my project https://github.com/Secure-Labs/nextgen more specifically I'm trying to use `CK_LIST` but I can't find any documentation or examples other than the regression test that come with concurrencykit. I figured out how to use `CK_LIST`  in a single process but when I try to use `CK_LIST` from shared memory between two processes the values in `CK_LIST` are garbage. This stackoverflow question shows examples: http://stackoverflow.com/questions/32361619/how-to-share-ck-list-across-processes .

**Comment by sbahra** [comment]
Cool project! CK_LIST is a single-writer many-reader list that is a search-and-replace replacement for BSD-style queue.h. The online manual page is plagued by a man2html bug, but local man page should point this out. If you're using it in the context of multiple address spaces, you need to make sure that the addresses are consistent (including the backing) across the address spaces, this is a problem for any pointer-based data structure. A cursory scan of the example code provided indicates that no such guarantees are made for the actual data or list items (see the usage of malloc).

For future reference, there is a Google Group / mailing list that can be used for such discussions or questions, issues are good for work tracking on the other hand. Let me know if you've other questions!
