### ISSUE TITLE
ck_epoch documentation out of date

### ISSUE THREAD

**Issue by mattmacy** [concurrencykit/ck#76]
A number of the ck_epoch functions take an extra argument now. Discovering this at compile time rather than from the man pages is a bit disconcerting.

**Comment by cognet** [comment]
Hi,

I just checked the manpages, and beside ck_epoch_poll which was indeed outdated and claimed an extra arg, I see no error, can you be more specific ?

Thanks !

**Comment by mattmacy** [comment]
https://reviews.freebsd.org/D6696

Basically any place you see a NULL passed to a ck_epoch function. The two that stand out are ck_epoch_begin and ck_epoch_end. The man pages make no mention of a ck_epoch_section_t that I saw (I may have overlooked it).

**Comment by sbahra** [comment]
They do: http://concurrencykit.org/doc/ck_epoch_begin.html http://concurrencykit.org/doc/ck_epoch_end.html - however, section is incorrectly documented as mandatory. Will fix and close.

**Comment by mattmacy** [comment]
http://concurrencykit.org/doc/ck_epoch_barrier.html 
This is the main code example I used as reference. It doesn't use sections.

**Comment by mattmacy** [comment]
I didn't look at the ck_epoch_{begin, end} because they had no usage example.

**Comment by mattmacy** [comment]
I see now. I'm sorry for the noise. What is the benefit of the epoch being refreshed on recursion?

**Comment by mattmacy** [comment]
Feel a bit sheepish. Will close and just assume that you'll update the epoch_barrier example and clarify the benefit of epoch refresh.

**Comment by sbahra** [comment]
haha, please don't feel sheepish. Thanks for bringing this to our attention.
