### ISSUE TITLE
configure expects CC to be found in PATH

### ISSUE THREAD

**Issue by mdcallag** [concurrencykit/ck#90]
I was trying to build another project that included concurrencykit and need to set a path for my compiler. My compiler isn't in PATH. The configure command line for ck was something like:
CC=/really/long/path/to/my/gcc ./configure

With that ck uses /bin/gcc because $CC isn't found in my $PATH - see use of pathsearch in https://github.com/concurrencykit/ck/blob/master/configure#L563

My diff to get a working build is below. The idea for the diff is that if the user provided a value for CC then it can be used.

--- a/third_party/concurrency_kit/ck/configure
+++ b/third_party/concurrency_kit/ck/configure
@@ -560,11 +560,13 @@ else
        GZIP_SUFFIX=".gz"
 fi

-printf "Finding suitable compiler........"
+printf "Finding suitable compiler........ ${CC:-cc}"
+if test -z "$CC" ; then
 CC=`pathsearch "${CC:-cc}"`
 if test -z "$CC" -o ! -x "$CC"; then
        CC=`pathsearch "${CC:-gcc}"`
 fi
+fi
 assert "$CC" "not found"

 cat << EOF > .1.c

**Comment by sbahra** [comment]
Fix committed, thanks!
