### ISSUE TITLE
Is it possible to make ck available on Android & IOS?

### ISSUE THREAD

**Issue by guijun** [concurrencykit/ck#94]
I tried and I failed to run configure.
Detecting operating system.......success [darwin]
Detecting machine architecture...success [arm]
Finding dirname command..........success [/usr/bin/dirname]
Determining build directory......success [/Users/kin/Documents/ude4/kmc_engine_ext/thirdparty/src/ck]
Finding gzip tool................success [/usr/bin/gzip]
Finding suitable compiler........./configure: line 599: ./.1: cannot execute binary file
failed  [update compiler]

**Comment by sbahra** [comment]
@guijun It should be easy. What would it take to make it available on there? Happy to work with you on making that happen.

**Comment by guijun** [comment]
is all api ck using are available on android and ios？
if YES， I want to try it by adjusting configure

**Comment by sbahra** [comment]
@guijun Yes, for src/ and include/. No for regressions, but that should be fine.

**Comment by guijun** [comment]
I'm testing ck_ht and if I add key/value pair since 01 00 00 00 to 0x ff ff ff 00 ,  many hash collisions happen and many keyvalue lost

**Comment by sbahra** [comment]
@guijun What did you need to do to get Android / iOS builds going? Can we work together so the work you did here gets included in the next Concurrency Kit release?

Let's track your ck_ht issues in the other ticket you created.

**Comment by guijun** [comment]
I added a CMakeLists.txt and make it buildable for android.
but the CMakeLists.txt depends on my game engine, so It's not ok to be included in CK release yet.

Now I'm trying it on Mac, and I'll try it on android, ios asap.

**Comment by sbahra** [comment]
Thanks @guijun. Patches are welcome for this. Could you share your CMakeLists file?

**Comment by sbahra** [comment]
@guijun Hi. Any updates on this? Otherwise, I'll close the ticket.
