### ISSUE TITLE
ck_ht usage

### ISSUE THREAD

**Issue by guijun** [concurrencykit/ck#95]
Please find test code and comments below:
        std::map<int,void*> stdMap;
        MC::Concurrency::HashTable htSPMC(CK_HT_MODE_BYTESTRING,MC::Concurrency::HashTable::Mode::M_MPMC);
        char* data="123";
        for(int i=1;i<50000;++i)
        {
            stdMap[i]=(void*)i;
            htSPMC.Set((char*)(&i),sizeof(i),(void*)i);
        };
        printf("remaining %d %d\n",stdMap.size(), htSPMC.Size());
---> We got  49999 49999
        for(int i=1;i<50000;++i)
        {
            stdMap[i]=(void*)i;
            htSPMC.Set((char*)(&i),sizeof(i),(void*)i);
        };
        printf("remaining %d %d\n",stdMap.size(), htSPMC.Size());
---> We got  49999 50316

**Comment by guijun** [comment]
If we run the loop again,
we will get remaining 49999 50633.

please find HashTable constructor below: 

HashTable::HashTable(unsigned int a_ht_mode,Mode a_mode)
        :mode_(a_mode)
        {
            
            ck_epoch_init(&epoch_ht);
            ck_epoch_register(&epoch_ht, &epoch_wr);
            common_srand48((long int)time(NULL));
            
            
            if (ck_ht_init(&ht_,a_mode, ht_hash_wrapper, &allocator_, 8, common_lrand48())==false) {
                perror("ck_ht_init");
                exit(EXIT_FAILURE);
            };
            ck_spinlock_init(&writeLock_);
        };

**Comment by sbahra** [comment]
@guijun It's easy to misuse ck_ht, unfortunately. Could you try ck_hs instead and report whether you see this problem?

It's hard for me to help you since I'm unsure how your C++ wrappers are interacting with things.

**Comment by guijun** [comment]
Hi, I'm sorry I don't know how to save k/v pair in ck_hs ...
And, please find wrapper below:
      bool HashTable::Set(char* a_key, uint32_t a_keyLength, void* a_value)
        {
            ck_ht_hash_t hash{0};
            ck_ht_entry_t entry; 
            ck_ht_hash(&hash,&ht_,a_key,a_keyLength);
            ck_ht_entry_set(&entry,hash,a_key,a_keyLength,a_value);
            switch(mode_)
            {
                case M_SPMC:
                    break;
                case M_MPMC:
                    ck_spinlock_lock(&writeLock_);
                    break;
            }
            bool result=ck_ht_set_spmc(&ht_, hash, &entry);
            switch(mode_)
            {
                case M_SPMC:
                    break;
                case M_MPMC:
                    ck_spinlock_unlock(&writeLock_);
                    break;
            }
            if(result)
            {
                if(entry.key && entry.value)
                {
                    int nothing=1;
                }
                else
                {
                    int nothing=1;
                }
                if(eraseProc_)
                {
                    eraseProc_((char*)ck_ht_entry_key(&entry),ck_ht_entry_key_length(&entry),ck_ht_entry_value(&entry));
                };
            }
            else
            {
                                    int nothing=1;
            }
            return result;
        };

**Comment by sbahra** [comment]
ck_hs is better if you can derive the key from the object. For example,

```
struct poop {
    int value;
    char key[];
};
```

You can use `container_of` like function to get from address of key to `struct poop` container. You will get significantly better performance and let's difficult to use. ck_ht API was an experiment in "make it harder for developers to write non-performant hash table interaction", which ended up with something that most folks use wrong the first time.

You need to make sure:
1) You are using consistent hash values, above looks suspect.
2) Key length is less than CK_HT_KEY_LENGTH.
3) Value of key is not 0 or ~0 (these are sentinels).

**Comment by sbahra** [comment]
@guijun Any updates on this? Otherwise, I'll close the ticket.
