### ISSUE TITLE
Unable to build on MSYS2

### ISSUE THREAD

**Issue by ckkashyap** [concurrencykit/ck#96]
Hi,
I was attempting to build concurrencykit on msys2 and the configure script complained about being an "unsupprted" system. I was able to make the following change and get the whole thing to work.

```
diff --git a/configure b/configure
index dd78d76..d2ac714 100755

--- a/configure
+++ b/configure
@@ -351,6 +351,10 @@ case "$SYSTEM" in
                SYSTEM=mingw32
                LDFLAGS="-mthreads $LDFLAGS"
                ;;
+       MSYS_NT*)
+               SYSTEM=mingw32
+               LDFLAGS="-mthreads $LDFLAGS"
+               ;;
   CYGWIN_NT*)
     SYSTEM=cygwin
     LDFLAGS="-mthreads $LDFLAGS"
```

So it built cleanly on 32bit and 64bit variants of msys2. It would be really nice if this change is pulled in. Please let me know if you need anything more from me for this.

Regards,
Kashyap

**Comment by cognet** [comment]
Hi, 

I pushed something similar, is it ok for you ?

Thanks !

**Comment by ckkashyap** [comment]
Absolutely :)

**Comment by cognet** [comment]
Thanks :)
