### ISSUE TITLE
libck.so name collision with the charm project

### ISSUE THREAD

**Issue by hydrapolic** [concurrencykit/ck#97]
During building of multiple packages on Gentoo it was found that both concurrencykit and charm try to install libck.so in /usr/lib/libck.so. These are two completely different packages, but this means users cannot have them installed on a single machine in parallel.

Would it be possible to change the library name? For example concurrencykit should be unique :)

http://charm.cs.uiuc.edu/software

**Comment by sbahra** [comment]
Hi @hydrapolic - this will be terribly annoying for most existing users of Concurrency Kit, including myself (sweeping update of build scripts and package dependencies). I don't think we'll be changing the name at the moment unless there is a lot more compelling reason.

What if the library is called libconcurrencykit just on Ubuntu? Let me know if there's anything we can do upstream to help with this.

**Comment by hydrapolic** [comment]
@sbahra, we added a blocker hoping that nobody wants concurrencykit with charm in parallel :)

**Comment by sbahra** [comment]
@hydrapolic Ok, thanks! Also, I meant s/Ubuntu/Gentoo/. Let me know if you want us to update configure script to allow more customization around the library basename.
